squire = {
  firstname: "Rogar",
  lastname: "Wideswing",
  email: "bigvikingboy@gmail.com",
  gender: "M",
  country: "Dragon Council State",
  isSquireApprenticed: false,
  favoriteMartialArts: [
    "Fortification",
    "Gr. Fortification",
    "Dexterity Boost",
    "Gr. Dexterity Boost",
    "Slash",
    "Duo Slash",
  ],
  totalSpentOnExp: 10.0,
};

squires = [
  {
    firstname: "Rogar",
    lastname: "Wideswing",
    email: "bigvikingboy@gmail.com",
    gender: "M",
    country: "Dragon Council State",
    isSquireApprenticed: false,
    favoriteMartialArts: [
      "Fortification",
      "Gr. Fortification",
      "Dexterity Boost",
      "Gr. Dexterity Boost",
      "Slash",
      "Duo Slash",
    ],
    totalSpentOnExp: 10.0,
  },
  {
    firstname: "Garrison",
    lastname: "Zamora",
    email: "garrisonZamora@yggdrasil.net",
    gender: "M",
    country: "High Theocracy",
    isSquireApprenticed: false,
    favoriteMartialArts: [
      "Taunt",
      "Gr. Taunt",
      "Dexterity Boost",
      "War Rally",
      "Rush",
      "Stampede",
    ],
    totalSpentOnExp: 9.52,
  },
  {
    firstname: "Bettie",
    lastname: "Gaines",
    email: "bettieGaines@yggdrasil.net",
    gender: "F",
    country: "Dragon Council State",
    isSquireApprenticed: false,
    favoriteMartialArts: [
      "Fortification",
      "Gr. Fortification",
      "Dexterity Boost",
      "War Rally",
      "Rush",
      "Duo Slash",
    ],
    totalSpentOnExp: 5.81,
  },
  {
    firstname: "Polly",
    lastname: "Bush",
    email: "pollyBush@yggdrasil.net",
    gender: "F",
    country: "High Theocracy",
    isSquireApprenticed: true,
    favoriteMartialArts: [
      "Taunt",
      "Gr. Taunt",
      "War Cry",
      "War Rally",
      "Rush",
      "Stampede",
    ],
    totalSpentOnExp: 2.49,
  },
  {
    firstname: "Taylor",
    lastname: "Shepard",
    email: "taylorShepard@yggdrasil.net",
    gender: "M",
    country: "Dragon Council State",
    isSquireApprenticed: true,
    favoriteMartialArts: [
      "Fortification",
      "Gr. Taunt",
      "Dexterity Boost",
      "Gr. Dexterity Boost",
      "Slash",
      "Duo Slash",
    ],
    totalSpentOnExp: 7.53,
  },
  {
    firstname: "Concetta",
    lastname: "Trujillo",
    email: "concettaTrujillo@yggdrasil.net",
    gender: "F",
    country: "Khanish States",
    isSquireApprenticed: false,
    favoriteMartialArts: [
      "Fortification",
      "Gr. Taunt",
      "War Cry",
      "War Rally",
      "Rush",
      "Stampede",
    ],
    totalSpentOnExp: 3.29,
  },
];
